### ISSUE TITLE
MacOS Ventura Beta support

### ISSUE THREAD

**Issue by jharingkaye** [raivo-otp/macos-receiver#15]
I am running the Beta 4 version of Ventura (MacOS 13). The Raivo app is still installed on the iPhone and on the MacBook and both appear to run normally. However, the receiver does not appear to get the passwords from the app. I have tried reconnecting the app and receiver with no luck. The receiver works as expected on another Macbook with MacOS 12.

**Comment by tabasko78** [comment]
Hi the same situation. Works fine on my MacBook macOS 13.
But impossible to "connect" via my iMac (even if I delete from recievers before trying to add again).
It's says it's ok from the iPhone, but impossible to connect the receiver from my iMac (even if it appears in the recievers list). I'm runing version 1.0.4 from App Store

**Comment by tijme** [comment]
Hmm, I've just updated to Venture, works fine on my side. Was it due to the beta and does it work now?

**Comment by tabasko78** [comment]
Unfortunately, it's always the same.
I have the notification on the iPhone that says it's OK, but still nothing on my iMac (Ventura) intel .
On my Macbook Ventura M1, it works.



----------------------
Raffi Mardirossian
https://www.123boost.com
06 12 86 82 96

**Comment by tabasko78** [comment]
Unfortunately, it's always the same.
I have the notification on the iPhone that says it's OK, but still nothing on my iMac (Ventura) intel .
On my Macbook Ventura M1, it works.

==> Do I have to download from here ? (I have reinstalled via AppStore in my last try)

**Comment by jharingkaye** [comment]
It is still the same for me.... I am running a M1 MacBook Pro 14". When I pull up console, I get the following error messages

`default	13:17:23.843394-0400	runningboardd	Invalidating assertion 422-408-1266 (target:[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333]) from originator [osservice<com.apple.WindowServer(88)>:408]
default	13:17:23.879662-0400	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] from originator [osservice<com.apple.WindowServer(88)>:408] with description <RBSAssertionDescriptor| "FUSBProcessWindowState: occluded" ID:422-408-1364 target:1333 attributes:[
	<RBSDomainAttribute| domain:"com.apple.fuseboard" name:"Occluded" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
default	13:17:23.879905-0400	runningboardd	Assertion 422-408-1364 (target:[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333]) will be created as active
default	13:17:23.881274-0400	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>: running-active (role: UserInteractive)
default	13:17:23.881357-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring jetsam update because this process is not memory-managed
default	13:17:23.881397-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring suspend because this process is not lifecycle managed
default	13:17:23.881411-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring GPU update because this process is not GPU managed
default	13:17:23.881431-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring memory limit update because this process is not memory-managed
default	13:17:23.882023-0400	runningboardd	Invalidating assertion 422-408-1267 (target:[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333]) from originator [osservice<com.apple.WindowServer(88)>:408]
default	13:17:23.964636-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring jetsam update because this process is not memory-managed
default	13:17:23.964672-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring suspend because this process is not lifecycle managed
default	13:17:23.964672-0400	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>: running-active (role: UserInteractive)
default	13:17:23.964689-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring GPU update because this process is not GPU managed
default	13:17:23.965133-0400	runningboardd	[app<application.me.tij.Raivo-MacOS.32473048.32473065(501)>:1333] Ignoring memory limit update because this process is not memory-managed
error	13:17:30.014990-0400	apsd	<APSCourier 0x14880a000 production>: Ignoring duplicate message received with topic: 'me.tij.Raivo-MacOS' timestamp=1667409449662156983 (50.9 seconds ago)
default	13:17:30.015026-0400	apsd	APSPowerLog: {event: PC APSD Message Received, dict: {
    IsWakingMessage = 0;
    MessageIdentifier = 357366853;
    Priority = 0;
    ServerHostname = "40-courier.push.apple.com.";
    ServerIP = "17.57.144.245";
    Size = 445;
    StorageFlag = 0;
    Topic = "me.tij.Raivo-MacOS";
}}
`

**Comment by alexdohmen** [comment]
> Hmm, I've just updated to Venture, works fine on my side. Was it due to the beta and does it work now?

No it is the same for released version and updates

**Comment by tabasko78** [comment]
Still not working for me on macos ventura on my iMac (2017)
(works fine on macbook pro m1 (2021) macos ventura

Is it supposed to be fixed for iMac macos ventira /intel ?

**Comment by rootedetc** [comment]
Same here, MacBook Pro 2019, intel CPU.
Doesn't work since the update to Ventura

**Comment by SenorLoco** [comment]
Add me to the list of those having problems with the receiver not receiving anything since upgrading to Ventura 13.0 (22A380) on my M1 MacBook Pro.  I've reinstalled the receiver and the app on my iPhone is showing the Mac, but nothing is received.

**Comment by TehPsychedelic** [comment]
This is a bit of a useless comment but downloaded this today on my new MacBook M1 Pro (2021), latest Ventura, and the app doesn't even run for me. Didn't take a look at the logs. But then realized this was just a receiver.

So I installed the iPad app and it works perfectly, biometrics and all—just a temporary solution for those who want the receiver and are on ARM + Ventura.

**Comment by mcmehrtens** [comment]
I'm not having any issues with the Raivo OTP receiver. I had the application installed before macOS Ventura on my 14" MacBook Pro M1 (2021) and after updating to macOS Ventura, I've had no issues.

**Comment by tijme** [comment]
Will hopefully be fixed in version 1.0.5. Works for me at least (famous last words).

Let me know! 1.0.5 will be published once Apple approved it.

**Comment by mcmehrtens** [comment]
I noticed the title change. I have noticed that notifications were not working since my update to macOS Ventura. I will follow-up if version 1.0.5 fixes this.

**Comment by gkarag** [comment]
I tried the latest version 1.0.5 of the receiver app on both Intel and M1 macs. I have removed and relinked it first. Notifications don't seem to be working in both cases.

**Comment by SenorLoco** [comment]
I too am still having the same issue with 1.0.5.  Uninstalled the receiver restarted my computer, reinstalled and re-linked but still no notifications on my Mac.

**Comment by tijme** [comment]
Hmm, this is awkward. To be honest, I don't have any clue why notifications are not working at the moment. The classic 'it works on my machine' applies here. 

I need to do some further debugging on why notifications aren't working. But as I can't reproduce the issue yet, it's kind of difficult for me. I'll let you know if I have any update on this.

Please let me know if you have any more information as well!

**Comment by jharingkaye** [comment]
I am guessing that with the macOS upgrade, something must have happened to mess up the registration and entitlements of the app. I wiped and reinstalled macOS and it appears to work now. It also could have something to do with me still being on beta previously.

**Comment by mcmehrtens** [comment]
Is there a way to access debug logs? I can attempt to build the code and do some debugging, but I have limited experience with macOS development.

**Comment by mcmehrtens** [comment]
Ahh, that's fascinating. I noticed that the Receiver appeared to be "working" even after I removed my MBP (Apple Silicon) as a receiver. Silly me, it was actually not working. Apple's Handoff feature was just pasting the text on my MBP from the iPhone clipboard.

After disabling Handoff on my Mac (System Settings -> General -> AirDrop and Handoff -> Uncheck "Allow Handoff between this Mac and your iCloud devices"), the Raivo OTP macOS receiver is NOT working for me on macOS 13.1. No notifications or copy/paste functionality.

**Comment by jharingkaye** [comment]
I have been using Console to see what’s going on.Joshua Ilya Haring-KayeOwner, jnoyz entertainmentOwner, fubrico LLCOn Dec 14, 2022, at 12:08, Matthew Mehrtens ***@***.***> wrote:﻿
Ahh, that's fascinating. I noticed that the Receiver appeared to be "working" even after I removed my MBP (Apple Silicon) as a receiver. Silly me, it was actually not working. Apple's Handoff feature was just pasting the text on my MBP from the iPhone clipboard.
After disabling Handoff on my Mac (System Settings -> General -> AirDrop and Handoff -> Uncheck "Allow Handoff between this Mac and your iCloud devices"), the Raivo OTP macOS receiver is NOT working for me on macOS 13.1. No notifications or copy/paste functionality.

**Comment by SenorLoco** [comment]
I've been bored at work so I've been playing around a bit and I believe the app itself is fine but (from my untrained eye) there is something wrong with the APNs and the push token.  I was able to load Raivo OTP on my Guest user account, registered it with my phone and it was able to receive notifications successfully.  Unfortunately when I removed that receiver and went back to my main account on my mac it still wasn't working nor did it work after reregistering my Guest account.

**Comment by jharingkaye** [comment]
SenorLoco,Those are my observations as well. Before I reinstalled macOS, I would get “duplicate message for topic … ignoring” in the console for the APN service. Joshua Ilya Haring-KayeOwner, jnoyz entertainmentOwner, fubrico LLCOn Dec 14, 2022, at 13:04, SenorLoco ***@***.***> wrote:﻿
I've been bored at work so I've been playing around a bit and I believe the app itself is fine but (from my untrained eye) there is something wrong with the APNs and the push token.  I was able to load Raivo OTP on my Guest user account, registered it with my phone and it was able to receive notifications successfully.  Unfortunately when I removed that receiver and went back to my main account on my mac it still wasn't working nor did it work after reregistering my Guest account.

**Comment by tijme** [comment]
I've added debug logging to version 1.0.6. This version will be released within a few days (as soon as Apple approves it). In the settings screen, you can enable debug logging and it will log possible errors/exceptions to a file which you can open. It might help debug the issue, as I'm still unable to reproduce it.

**Comment by tijme** [comment]
> I've been bored at work so I've been playing around a bit and I believe the app itself is fine but (from my untrained eye) there is something wrong with the APNs and the push token. I was able to load Raivo OTP on my Guest user account, registered it with my phone and it was able to receive notifications successfully. Unfortunately when I removed that receiver and went back to my main account on my mac it still wasn't working nor did it work after reregistering my Guest account.
> 
> edit: I should mention that the push token on the guest account was different than the one on my main account

By the way, if this is the case, then I'm not sure how to fix it. Do you have any ideas? I'm having trouble finding related cases on the internet.

**Comment by tijme** [comment]
I've asked StackExchange for help as well. https://stackoverflow.com/questions/74868553/apple-push-notifications-arriving-on-macos-but-not-application-itself

**Comment by tijme** [comment]
I've just updated the production key to a new one. However, as it used to be working at my machine already, would you be so kind to test if your production installation of Raivo now works? 😄 

Thanks in advance!

**Comment by mcmehrtens** [comment]
Prompted by your conversation with @exquisitetelescope, I updated my version of Raivo OTP Receiver on my MBP to the newest version with a debug log. Using my iPhone, I re-added my MBP as a receiver and attempted to copy a OTP. I didn't receive any notification. This is all my debug file said:

[raivo-debug-log.txt](https://github.com/raivo-otp/macos-receiver/files/10287690/raivo-debug-log.txt)

**Comment by tijme** [comment]
That's so interesting. If you open `Console.app` and filter on `aps` you'll probably see the notification coming in. Somehow it's just not ending up in the app...

**Comment by mcmehrtens** [comment]
Correct. I am received the apsd notifications in Console.app.
[console_log.txt](https://github.com/raivo-otp/macos-receiver/files/10287844/console_log.txt)
[raivo-debug-log.txt](https://github.com/raivo-otp/macos-receiver/files/10287846/raivo-debug-log.txt)

**Comment by tijme** [comment]
Just for the extra info. I just checked the `Console.app` output on my machine, on which notifications work. I get the following output:

```default	16:00:48.398766+0100	apsd	<private>: Message for topic <private> for user <private> piggybacking on push wake
default	16:00:48.398808+0100	apsd	<private>: Message has token <private> (tokenName <private>)
default	16:00:48.398969+0100	apsd	<private>: Received message for enabled topic '<private>' onInterface: NonCellular with payload '<private>' with priority 5
default	16:00:48.399208+0100	apsd	<private>: Push has been read from stream and parsed. UUID: (null)
default	16:00:48.399323+0100	apsd	APSPowerLog: {event: <private>, dict: <private>}
default	16:00:48.399481+0100	apsd	<private> asked to store incoming message <private> with guid <private> environment <private>
```

In contrast to the `Console.app` logging for people where notifications do not work ( I see that @mcmehrtens just also uploaded this log):

```default 20:35:11.555463+0100    apsd    <private>: Outstanding data received: <private> (length 490)
default 20:35:11.555624+0100    apsd    <private>: Stream processing: complete yes, invalid no, length parsed 490, parameters <private>
default 20:35:11.555761+0100    apsd    <private>: Failed to find token name for unrecognized token <private>
default 20:35:11.555876+0100    apsd    <private>: Message has token <private> (tokenName (null))
error   20:35:11.556008+0100    apsd    <private>: Received message for unknown token '<private>'
error   20:35:11.556068+0100    apsd    <private>: Ignoring duplicate message received with topic: '<private>' timestamp=1671564911431255965 (57.5 seconds ago)
default 20:35:11.556186+0100    apsd    APSPowerLog: {event: <private>, dict: <private>}
default 20:35:11.556432+0100    apsd    <private>: Sending acknowledgement message with response 7 and messageId <private> (3889788835)
default 20:35:11.556591+0100    apsd    <private>: Sending Push ACK. UUID: (null)
default 20:35:11.556735+0100    apsd    <private>: Stream processing: complete no, invalid no, length parsed 0, parameters (null)```

So I believe it's related to these lines, which I'll do some more research on: 

```error   20:35:11.556008+0100    apsd    <private>: Received message for unknown token '<private>'
error   20:35:11.556068+0100    apsd    <private>: Ignoring duplicate message received with topic: '<private>' timestamp=1671564911431255965 (57.5 seconds ago)```

**Comment by mcmehrtens** [comment]
Yes, I get the same output from aspects status.

**Comment by tijme** [comment]
As far as I can see, my push notification token never changed. Some users have reported that after the MacOS receiver stopped working, they re-added their receiver to the iOS app by rescanning the QR-code, which means they would have the correct push notification token, as the QR code contains the current push notification token.

**Comment by mcmehrtens** [comment]
I'll caveat this here by saying I've never programming in Swift or built an iOS/macOS application, but according to this documentation, it seems like the push notification token is supposed to be refreshed once an hour?

https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/establishing_a_token-based_connection_to_apns

At the end it says,

> For security, APNs requires you to refresh your token regularly. Refresh your token no more than once every 20 minutes and no less than once every 60 minutes. APNs rejects any request whose token contains a timestamp that is more than one hour old. Similarly, APNs reports an error if you recreate your tokens more than once every 20 minutes.
On your provider server, set up a recurring task to recreate your token with a current timestamp. Encrypt the token again and attach it to subsequent notification requests.

**Comment by tijme** [comment]
Correct. Thanks for thinking along though @mcmehrtens. The page you linked is about the token being used on the APNS server. Here to be exact: https://github.com/raivo-otp/apns-server/blob/master/public/v1/apns.php#L114.

The token is a JSON Web Token, calculated on the fly once someone pushes an OTP token in the iOS app. This is against the Apple specs apparently, now that I read those docs (because they must not be refreshed more often than once every 20 minutes.

According to the docs, the Apple APS server should report an error if a token is refreshed to often. In contrast to their docs, they do not respond with such an error to my APNS server.

I'll take a look at it a little more to see if this could be an issue.

**Comment by mcmehrtens** [comment]
That all makes sense. Thanks for taking the time to elaborate. I'll keep digging.

**Comment by mcmehrtens** [comment]
It's strange that it didn't change your device token. Isn't this saying it should have changed?

> Never cache device tokens in local storage. APNs issues a new token when the user restores a device from a backup, when the user installs your app on a new device, and when the user reinstalls the operating system. If you ask the system to provide the token each time, you’re guaranteed to get an up-to-date token.

[Source](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns)

**Comment by mcmehrtens** [comment]
https://eclecticlight.co/2020/05/25/how-to-reveal-private-messages-in-the-log/
https://georgegarside.com/blog/macos/sierra-console-private/

Not sure if this is helpful, but this profile allows you to un-<private> your logs in console. I just turned this on to see if it yields any useful information... Maybe this is already well-known!

**Comment by mcmehrtens** [comment]
No, I haven't tried that yet. I will try it later tonight, noting my device token before and after.

**Comment by mcmehrtens** [comment]
Check my understanding here:

Whenever the Raivo OTP Receiver launches, it registers itself with APNS, and, if successful, receives a device token from APNS (the push notification token). When I link this receiver (my MBP) to the iOS app, the iOS Raivo app associates that device token with my MBP, and upon pressing a OTP, it tells APNS to send a remote notification to the associated device token.

APNS then processes that request and sends the notification to my MacBook. apsd receives this notification from APNS and tries to find a local application with the matching device token. The console errors seem to imply that apsd is having troubles associating the device token with the Raivo OTP Receiver.

As an aside, at some point in iOS/macOS development, there used to only be one device token per device. Apple has since changed the device token to be unique for each application so that a device token cannot be used a personal identifier between apps. This explains why changing the bundle ID for the application changes the device token.

**Comment by mcmehrtens** [comment]
If my understanding is correct (or fairly correct), then this is what I can come up with for points of failure:

- APNs is receiving invalid information from the Raivo OTP Receiver (perhaps the part of the token that identifies the device is correct, but the part associated with a specific application is incorrect)
- APNs is providing the Raivo OTP Receiver with an invalid device token (unlikely--probably safe to assume that APNs is functioning correctly)
- apsd is unable to correlate the device token with the Raivo OTP Receiver application

With all that said, I agree with @exquisitetelescope that apsd seems to be the most likely point of failure. Am I missing any possible failure points here?

I'm going to do some digging into apsd now that I (think I) have a better understanding of the problem...

**Comment by mcmehrtens** [comment]
@exquisitetelescope No, I’ve not been running macOS Ventura Beta at any point during my testing.

I’m currently re-installing macOS to see if that (temporarily) resolves the problem.

**Comment by mcmehrtens** [comment]
> Hopefully not yet! I just figured out the fix.
> 
> But if so, do let me know if the reinstall fixes it.

Reinstalling macOS did not reset my device token or resolve the issue.



> Potential fix for those impacted:
> 
> 1. Backup `~/Library/Preferences/com.apple.ncprefs.plist` (can save it to Desktop).
> 2. Remove the apps section of `~/Library/Preferences/com.apple.ncprefs.plist` (you can Xcode to edit this).
> 3. sudo killall NotificationCenter && killall usernoted
> 4. Reboot
> 
> This will clear all of your notification preferences and you will have to re-approve each app when prompted.

Trying this now.

**Comment by SenorLoco** [comment]
> Potential fix for those impacted:
> 
> 1. Backup `~/Library/Preferences/com.apple.ncprefs.plist` (can save it to Desktop).
> 2. Remove the apps section of `~/Library/Preferences/com.apple.ncprefs.plist` (you can Xcode to edit this).
> 3. sudo killall NotificationCenter && killall usernoted
> 4. Reboot
> 
> This will clear all of your notification preferences and you will have to re-approve each app when prompted.

This seems to have fixed it for me.

**Comment by mcmehrtens** [comment]
@exquisitetelescope Your steps also worked for me. I also tried a number of other steps leading up to deleting the entire apps field.

I tried:
- Only deleting the Push -> Token field for the Raivo dictionary entry
- Only deleting the Push field for the Raivo dictionary entry
- Only deleting the Raivo dictionary entry

None of those worked. Only deleting the entire Apps field and rebooting worked. How did you come to this solution?

**Comment by mcmehrtens** [comment]
Not to throw a wrench into this, but rebooting my computer seems to cause the bug to occur again. Can you confirm whether or not the fix lasts after another reboot?

[pre-fix.com.apple.ncprefs.plist.txt](https://github.com/raivo-otp/macos-receiver/files/10291348/pre-fix.com.apple.ncprefs.plist.txt)
[post-fix.com.apple.ncprefs.plist.txt](https://github.com/raivo-otp/macos-receiver/files/10291349/post-fix.com.apple.ncprefs.plist.txt)
[fixed.com.apple.ncprefs.plist.txt](https://github.com/raivo-otp/macos-receiver/files/10291350/fixed.com.apple.ncprefs.plist.txt)

Those three files are my ncprefs.plist file before the fix (pre-fix.*; broken receiver state), after applying @exquisitetelescope 's solution (fixed.*; working receiver state), and after rebooting once more (post-fix.*; broken receiver state).

**Comment by SenorLoco** [comment]
I've restarted a couple times and the fix is still working for me.  Instead of just deleted the apps section I just deleted the entire file...not sure if that did something different.

**Comment by mcmehrtens** [comment]
@exquisitetelescope @SenorLoco If you remove the receiver from the iOS app and re-add it, then reboot, does it still work?

**Comment by SenorLoco** [comment]
Removed and re-add the receiver and it has continued to work both before and after a reboot.

**Comment by mcmehrtens** [comment]
Additionally, this is the third time (twice consecutively) that I've tried the solution and it hasn't worked upon reboot. So the solution seems to work... sometimes (for some unfortunate users)?

**Comment by mcmehrtens** [comment]
This is beginning to feel like voodoo magic haha!

**Comment by mcmehrtens** [comment]
@exquisitetelescope I tried your revised fix of just deleting the file, clearing it from the recycle bin, and then rebooting immediately and it initially seemed like it worked. When I logged back in, I got the prompt from Raivo about enabling notifications.

But notifications still didn't work... It seems to me like there's almost certainly some Apple process that is ruining something. I can't imagine it's Raivo at this point.

**Comment by mcmehrtens** [comment]
@exquisitetelescope Unless you'd like me to try something for a while, I might call it a night on this and try to attack it with a fresh mind tomorrow. Perhaps @tijme will have some further insights.

**Comment by tijme** [comment]
Wow. You guys debugged a lot while I was asleep. How fantastic that you found a workaround to get notifications working again!!! I'll see if I can debug the issue a little more today.

FYI; I've also rewarded a 500 reputation bounty on SO for a helping hand; https://stackoverflow.com/questions/74868553/apple-push-notifications-arriving-on-macos-but-not-in-the-application-itself.

**Comment by tijme** [comment]
FYI; I've created a bug report at Apple too. If this is indeed a bug in MacOS or APS, I hope that speeds up the process. Bug reference FB11893580.

**Comment by tabasko78** [comment]
I tried to read and follow the posts (I am French). I confess that I am lost (and I am not dev).

I tried the solution by deleting the plist file, then sudo, then reboot... 

It's always the same on my MacOS Ventura Intel (on which everything worked fine before Ventura)

I re-installed Raivo
I launch it
I scan from my iPhone, which adds my macOS in the list of receivers, but still NOTHING on the Mac side.

Did I miss something ? or is it still bugged ?

**Comment by mcmehrtens** [comment]
@tijme Have you gotten any response from Apple yet regarding the bug? I want to continue helping with this, but I'm very busy in school right now. I can try to help develop a workaround as soon as I get some free time.

**Comment by tijme** [comment]
I filed a developer request and I'm currently in touch with an Apple engineer to debug the issue (had contact today). I'm hoping that he can see what's going wrong with all debug output he has access to. I sent him debug output from my side today.

**Comment by aronhoff** [comment]
I had this issue also, but an update to macOS 13.3 seems to have fixed it 🙃

**Comment by tabasko78** [comment]
On Apple App Store, Raivo version is still the same (last update 3 months ago).
From where do you get the fixed version ? I'm not very familiar with GibHub :-/

**Comment by mcmehrtens** [comment]
> On Apple App Store, Raivo version is still the same (last update 3 months ago).
> From where do you get the fixed version ? I'm not very familiar with GibHub :-/

No update of any Raivo application is necessary to get the fix. The bug was most likely a macOS bug which was fixed in the macOS 13.3 release that came out yesterday. If you update your Mac to macOS 13.3, your Raivo receiver should start working properly again.

**Comment by mcmehrtens** [comment]
@exquisitetelescope Did updating to macOS 13.3 fix this for you? It did for me.

**Comment by tabasko78** [comment]
Oh ! no ! not yet ! I'm going to do it right now

**Comment by tabasko78** [comment]
For me it still doesn't seem to work.

(I always start by deleting the macOS from the reciever list)

I launch the application on MacOs.
I do " Get started ". I get the QR code

Then, from my iPhone, I go to "Receivers", I add with the "+" button 

I scan the QR code.
On the iPhone, I have the mssage :

Connected
The MacOS device will now receive OTP's on tap !

-

On MacOS, it stays on the QR Code and that's all...
Even if I restart, I stay at the initial step with the "get started" proposal...



`2023-03-28 22:23:41  ApplicationPrincipal.initializeFileLogging():75 VERBOSE: File log destination initialized: file:///Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data/Library/Caches/Raivo%20OTP/raivo-debug-log.txt
2023-03-28 22:23:46  ApplicationDelegate.applicationDidFinishLaunching():56 VERBOSE: Status bar feature initialized.
2023-03-28 22:23:46  ApplicationDelegate.application():96 VERBOSE: Succesfully completed APNS registration process.
2023-03-28 22:29:57  ApplicationPrincipal.initializeFileLogging():75 VERBOSE: File log destination initialized: file:///Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data/Library/Caches/Raivo%20OTP/raivo-debug-log.txt
2023-03-28 22:29:57  ApplicationDelegate.applicationDidFinishLaunching():56 VERBOSE: Status bar feature initialized.
2023-03-28 22:29:57  ApplicationDelegate.application():96 VERBOSE: Succesfully completed APNS registration process.
2023-03-28 22:29:57 com.apple.usernotifications.UNUserNotificationServiceConnection.call-out ApplicationDelegate.applicationDidFinishLaunching():67 ERROR: Notifications are not allowed for this application`

**Comment by mcmehrtens** [comment]
> ERROR: Notifications are not allowed for this application

That error to me looks like you haven't allowed the Raivo Receiver to send notifications. Go to System Settings -> Notifications -> Raivo OTP and make sure Allow Notifications is ticked and the notification style is set to "Banners". Let me know if that fixes it for you.

**Comment by tabasko78** [comment]
This is what I looked at after seeing the log file.
But it doesn't fix my problem :(

`2023-03-28 23:12:01  ApplicationPrincipal.initializeFileLogging():75 VERBOSE: File log destination initialized: file:///Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data/Library/Caches/Raivo%20OTP/raivo-debug-log.txt
2023-03-28 23:12:01  ApplicationDelegate.applicationDidFinishLaunching():56 VERBOSE: Status bar feature initialized.
2023-03-28 23:12:01  ApplicationDelegate.application():96 VERBOSE: Succesfully completed APNS registration process.
`

**Comment by mcmehrtens** [comment]
> This is what I looked at after seeing the log file. But it doesn't fix my problem :(
> 
> `2023-03-28 23:12:01 ApplicationPrincipal.initializeFileLogging():75 VERBOSE: File log destination initialized: file:///Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data/Library/Caches/Raivo%20OTP/raivo-debug-log.txt 2023-03-28 23:12:01 ApplicationDelegate.applicationDidFinishLaunching():56 VERBOSE: Status bar feature initialized. 2023-03-28 23:12:01 ApplicationDelegate.application():96 VERBOSE: Succesfully completed APNS registration process. `

Are you seeing errors like this in your console/log file?

`error   20:35:11.556008+0100    apsd    <private>: Received message for unknown token '<private>'`
`error   20:35:11.556068+0100    apsd    <private>: Ignoring duplicate message received with topic: '<private>' timestamp=1671564911431255965 (57.5 seconds ago)`

This might be a separate problem. Nothing from that log file you just posted looks out of place. Can you attach the full log file?

**Comment by tabasko78** [comment]
Like this ? (console filtered on Raivo)

`par défaut	23:26:21.766617+0200	runningboardd	Launch request for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)> is using uid 502 (divined from auid 502 euid 502)
par défaut	23:26:21.766696+0200	runningboardd	Acquiring assertion targeting app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)> from originator [osservice<com.apple.Spotlight(502)>:1059] with description <RBSAssertionDescriptor| "LS launch me.tij.Raivo-MacOS" ID:187-1059-4433 target:app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)> attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LaunchRoleUserInteractive" sourceEnvironment:"(null)">
	]>
par défaut	23:26:21.766774+0200	runningboardd	Assertion 187-1059-4433 (target:app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>) will be created as active
par défaut	23:26:21.767070+0200	runningboardd	Executing launch request for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)> (LS launch me.tij.Raivo-MacOS)
par défaut	23:26:21.767303+0200	runningboardd	Checking PreventLaunch: global:0 exPath:/Applications/Raivo OTP.app/Contents/MacOS/Raivo OTP predicates:(null) allow:(null)
par défaut	23:26:21.767492+0200	runningboardd	Creating and launching job for: app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>
par défaut	23:26:21.767600+0200	runningboardd	_mutateContextIfNeeded called for me.tij.Raivo-MacOS
par défaut	23:26:21.768543+0200	runningboardd	app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: -[RBPersonaManager personaForIdentity:context:personaUID:personaUniqueString:] required 0.000954 ms (wallclock); resolved to {4294967295, (null)}
par défaut	23:26:21.769073+0200	runningboardd	'app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>' Constructed job description (context <RBSLaunchContext: 0x7faf5e79f3c0>):
<dictionary: 0x7faf6f1e0dc0> { count = 21, transaction: 0, voucher = 0x0, contents =
	"Platform" => <int64: 0xb2a21f2a14259a0d>: 1
	"ProcessType" => <string: 0x7faf6f1a26d0> { length = 3, contents = "App" }
	"EnableTransactions" => <bool: 0x7ff852733140>: false
	"_ManagedBy" => <string: 0x7faf6f123a90> { length = 22, contents = "com.apple.runningboard" }
	"CFBundleIdentifier" => <string: 0x7faf6f1b2ef0> { length = 18, contents = "me.tij.Raivo-MacOS" }
	"_ResourceCoalition" => <string: 0x7faf6f122cf0> { length = 64, contents = "app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>" }
	"ThrottleInterval" => <int64: 0xb2a218d5ebda7a0d>: 2147483647
	"MachServices" => <dictionary: 0x7faf6f1be660> { count = 0, transaction: 0, voucher = 0x0, contents =
	}
	"EnablePressuredExit" => <bool: 0x7ff852733140>: false
	"LimitLoadToSessionType" => <array: 0x7faf6f12ec50> { count = 2, capacity = <…>
par défaut	23:26:21.841177+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Memory Limits: active 0 inactive 0
 <private>
par défaut	23:26:21.841211+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] This process will not be managed.
par défaut	23:26:21.841231+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] HOME is <private>
par défaut	23:26:21.841309+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] TMPDIR is <private>
par défaut	23:26:21.841379+0200	runningboardd	Now tracking process: [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]
par défaut	23:26:21.841680+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:21.842291+0200	runningboardd	Using default underlying assertion for app: [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]
par défaut	23:26:21.842412+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] with description <RBSAssertionDescriptor| "RB Underlying Assertion" ID:187-187-4434 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.underlying" name:"defaultUnderlyingAppAssertion" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
par défaut	23:26:21.842680+0200	runningboardd	Assertion 187-187-4434 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:21.843393+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:21.843419+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:21.843580+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] reported to RB as running
par défaut	23:26:21.843543+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Set darwin role to: UserInteractive
par défaut	23:26:21.843863+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:21.844283+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:21.845175+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:21.847362+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.coreservices.launchservicesd>:140] with description <RBSAssertionDescriptor| "uielement:4269" ID:187-140-4435 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractive" sourceEnvironment:"(null)">
	]>
par défaut	23:26:21.847744+0200	runningboardd	Assertion 187-140-4435 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:21.849056+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:21.849881+0200	Spotlight	LAUNCH: 0x0-0xd00d0 me.tij.Raivo-MacOS starting stopped process.
par défaut	23:26:21.853619+0200	runningboardd	Invalidating assertion 187-1059-4433 (target:app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>) from originator [osservice<com.apple.Spotlight(502)>:1059]
par défaut	23:26:21.853818+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:21.854015+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:21.854459+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:21.854593+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:21.854770+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:21.854863+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:21.854978+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:21.855055+0200	runningboardd	Successfully acquired underlying assertion for [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]
par défaut	23:26:21.855259+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:21.864645+0200	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Raivo OTP.app
par défaut	23:26:21.868895+0200	secinitd	Raivo OTP[4269]: root path for bundle "<private>" of main executable "<private>"
par défaut	23:26:21.876949+0200	secinitd	AppSandboxUtilRealPathForUTF8StringPath(/Applications/Raivo OTP.app)
par défaut	23:26:21.885946+0200	secinitd	AppSandboxUtilRealPathForUTF8StringPath(/Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data)
par défaut	23:26:21.892942+0200	secinitd	AppSandboxUtilRealPathForUTF8StringPath(/Applications/Raivo OTP.app)
par défaut	23:26:21.893512+0200	secinitd	Raivo OTP[4269]: AppSandbox request successful
par défaut	23:26:21.896883+0200	Raivo OTP	Requesting container lookup; personaid = -1, type = NOPERSONA, name = <unknown>, origin [pid = 0, personaid = 0], proximate [pid = 0, personaid = 0], class = 2, identifier = <private>, group_identifier = <private>, create = 0, temp = 0, euid = 502, uid = 502
par défaut	23:26:21.896931+0200	Raivo OTP	Query; personaid = -1, type = NOPERSONA, name = <unknown>, origin [pid = 0, personaid = 0], proximate [pid = 0, personaid = 0], euid = 502, uid = 502, query = <private>
par défaut	23:26:21.904534+0200	appstoreagent	MDQuery changed app: <SoftwareItem: 0x7fb18374bd50>: (me.tij.Raivo-MacOS, 1.0.6, 1498497896:854008608 md:0x7fb184050050 /Applications/Raivo OTP.app)
par défaut	23:26:21.911756+0200	Raivo OTP	container_query_get_single_result: success
par défaut	23:26:21.911812+0200	Raivo OTP	Consuming sandbox extension; path = [<private>], key = 0
par défaut	23:26:21.911998+0200	Raivo OTP	Consuming sandbox extension; path = [<private>], key = 0
par défaut	23:26:21.912055+0200	Raivo OTP	Revoking sandbox extension; key = 0
par défaut	23:26:21.912106+0200	Raivo OTP	container_create_or_lookup_for_platform: success
par défaut	23:26:21.912163+0200	Raivo OTP	Revoking sandbox extension; key = 0
par défaut	23:26:21.911381+0200	containermanagerd	Using client sandbox path [<~~~>]; metadata = <<~~~>(2);<502/20/~~/0/1000>;u0D71A326-D942-4A9D-BC23-7CDD9EF32B25;pme.tij.Raivo-MacOS;dp-1;uma(null);L0>
par défaut	23:26:21.923250+0200	tccd	AUTHREQ_ATTRIBUTION: msgID=4269.1, attribution={requesting={TCCDProcess: identifier=me.tij.Raivo-MacOS, pid=4269, auid=502, euid=502, binary_path=/Applications/Raivo OTP.app/Contents/MacOS/Raivo OTP}, },
par défaut	23:26:21.927139+0200	tccd	AUTHREQ_SUBJECT: msgID=4269.1, subject=me.tij.Raivo-MacOS,
par défaut	23:26:21.928502+0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier me.tij.Raivo-MacOS, type: 0: 0x7f94321d9a00 at /Applications/Raivo OTP.app
par défaut	23:26:21.934231+0200	Raivo OTP	server port 0x00003707, session port 0x00003707
par défaut	23:26:21.936897+0200	tccd	AUTHREQ_ATTRIBUTION: msgID=169.205, attribution={accessing={TCCDProcess: identifier=me.tij.Raivo-MacOS, pid=4269, auid=502, euid=502, binary_path=/Applications/Raivo OTP.app/Contents/MacOS/Raivo OTP}, requesting={TCCDProcess: identifier=com.apple.WindowServer, pid=169, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer}, },
par défaut	23:26:21.936948+0200	tccd	requestor: TCCDProcess: identifier=com.apple.WindowServer, pid=169, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer is checking access for accessor TCCDProcess: identifier=me.tij.Raivo-MacOS, pid=4269, auid=502, euid=502, binary_path=/Applications/Raivo OTP.app/Contents/MacOS/Raivo OTP
par défaut	23:26:21.938528+0200	tccd	AUTHREQ_SUBJECT: msgID=169.205, subject=me.tij.Raivo-MacOS,
par défaut	23:26:21.939769+0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier me.tij.Raivo-MacOS, type: 0: 0x7f9432188db0 at /Applications/Raivo OTP.app
par défaut	23:26:21.948040+0200	Raivo OTP	New connection 0x7c563 main
par défaut	23:26:21.952938+0200	Raivo OTP	CHECKIN: pid=4269
par défaut	23:26:21.955873+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:21.955869+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:21.956134+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:21.956295+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:21.956551+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:21.981038+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.coreservices.launchservicesd>:140] with description <RBSAssertionDescriptor| "uielement:4269" ID:187-140-4438 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractive" sourceEnvironment:"(null)">
	]>
par défaut	23:26:21.981123+0200	runningboardd	Assertion 187-140-4438 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:21.980715+0200	launchservicesd	CHECKIN:0x0-0xd00d0 4269 me.tij.Raivo-MacOS
par défaut	23:26:21.981064+0200	Raivo OTP	CHECKEDIN: pid=4269 asn=0x0-0xd00d0 foreground=0
par défaut	23:26:21.983383+0200	Raivo OTP	FRONTLOGGING: version 1
par défaut	23:26:21.983483+0200	Raivo OTP	Registered, pid=4269 ASN=0x0,0xd00d0
par défaut	23:26:21.982707+0200	runningboardd	Invalidating assertion 187-140-4435 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) from originator [osservice<com.apple.coreservices.launchservicesd>:140]
par défaut	23:26:21.984033+0200	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Raivo OTP
par défaut	23:26:21.986411+0200	Raivo OTP	BringForward: pid=4269 asn=0x0-0xd00d0 bringForward=0 foreground=0 uiElement=1 launchedByLS=1 modifiersCount=1 allDisabled=0
par défaut	23:26:21.986922+0200	Raivo OTP	BringFrontModifier: pid=4269 asn=0x0-0xd00d0 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
par défaut	23:26:22.072957+0200	Raivo OTP	order window: 358 op: 1 relative: 358 related: 0
par défaut	23:26:22.082848+0200	Raivo OTP	Write options: 0 -- URL: <private> -- purposeID: 872DA281-39C2-4DF0-A99C-A760070607F6 -- claimID: 7ABEF797-B39D-47F4-8FC7-333CB98EF5B4
par défaut	23:26:22.083312+0200	filecoordinationd	Updating configuration of monitor <RBSProcessMonitorConfiguration| id:M650-51 qos:17 predicates:[<RBSProcessPredicate <RBSCompoundAllPredicate [<RBSProcessBundleIdentifierPredicate "me.tij.Raivo-MacOS">, <RBSCompoundAllPredicate [<RBSProcessBKSLegacyPredicate>, <RBSProcessEUIDPredicate 0>]>]>>] descriptor:<RBSProcessStateDescriptor| values:9 namespaces:[com.apple.frontboard.visibility]> events:0x0>
par défaut	23:26:22.083486+0200	Raivo OTP	[me.tij.Raivo-MacOS] Creating a user notification center
par défaut	23:26:22.083523+0200	Raivo OTP	[me.tij.Raivo-MacOS] Requesting authorization with options 7
par défaut	23:26:22.086787+0200	Raivo OTP	Adding presenter B9D4A9AD-22AB-430B-972F-92B136150516 for URL: <private>
par défaut	23:26:22.102144+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.WindowServer(88)>:169] with description <RBSAssertionDescriptor| "AppDrawing" ID:187-169-4443 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.appnap" name:"AppDrawing" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
par défaut	23:26:22.102221+0200	runningboardd	Assertion 187-169-4443 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:22.103102+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:22.103316+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:22.103562+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:22.103101+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:22.103938+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
erreur	23:26:22.105837+0200	usernoted	Push Client me.tij.Raivo-MacOS registered push with environment production with types 0, cloudkit: false
par défaut	23:26:22.105922+0200	usernoted	Registering me.tij.Raivo-MacOS for push on production with flags [ ]
par défaut	23:26:22.129198+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.WindowServer(88)>:169] with description <RBSAssertionDescriptor| "FUSBProcessWindowState: visible" ID:187-169-4445 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.fuseboard" name:"Visible" sourceEnvironment:"(null)">,
	<RBSAcquisitionCompletionAttribute| policy:AfterApplication>
	]>
par défaut	23:26:22.129288+0200	runningboardd	Assertion 187-169-4445 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:22.129538+0200	runningboardd	Deactivating delayed assertion 187-650-4439 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269])
par défaut	23:26:22.139491+0200	storekitagent	[Client] (Raivo OTP) Initialized with server Production bundle ID me.tij.Raivo-MacOS and request bundle ID me.tij.Raivo-MacOS]
par défaut	23:26:22.167767+0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier me.tij.Raivo-MacOS, type: 0: 0x7f94321b6140 at /Applications/Raivo OTP.app
par défaut	23:26:22.198674+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:22.198899+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:22.199063+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:22.199443+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:22.199661+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:22.263190+0200	Raivo OTP	sf changed: <private>
par défaut	23:26:22.426505+0200	storekitagent	[Client] (Raivo OTP) Initialized with server Production bundle ID me.tij.Raivo-MacOS and request bundle ID me.tij.Raivo-MacOS]
par défaut	23:26:22.454380+0200	storekitagent	[Client] (Raivo OTP) Initialized with server Production bundle ID me.tij.Raivo-MacOS and request bundle ID me.tij.Raivo-MacOS]
par défaut	23:26:22.511974+0200	storekitagent	No revocations in database for DSID: <private>, bundleID: me.tij.Raivo-MacOS
par défaut	23:26:22.526638+0200	storekitagent	[Client] (Raivo OTP) Initialized with server Production bundle ID me.tij.Raivo-MacOS and request bundle ID me.tij.Raivo-MacOS]
par défaut	23:26:23.094986+0200	Raivo OTP	Received configuration update from daemon (initial)
par défaut	23:26:23.205822+0200	runningboardd	Invalidating assertion 187-650-4450 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) from originator [osservice<com.apple.FileCoordination>:650]
par défaut	23:26:23.206123+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.FileCoordination>:650] with description <RBSAssertionDescriptor| "File Coordination Claim ACC828E2-FFD8-46FD-A8F0-8DCDC5736AE5" ID:187-650-4455 target:4269 attributes:[
	<RBSLegacyAttribute| requestedReason:FinishTask reason:FinishTask flags:( PreventTaskSuspend PreventTaskThrottleDown )>,
	<RBSAcquisitionCompletionAttribute| policy:AfterValidation>
	]>
par défaut	23:26:23.206171+0200	runningboardd	Assertion 187-650-4455 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as inactive as start-time-defining assertions exist
par défaut	23:26:23.208230+0200	Raivo OTP	Claim ACC828E2-FFD8-46FD-A8F0-8DCDC5736AE5 granted in client
par défaut	23:26:23.208244+0200	Raivo OTP	Claim ACC828E2-FFD8-46FD-A8F0-8DCDC5736AE5 invoked in client
par défaut	23:26:23.743010+0200	runningboardd	Invalidating assertion 187-650-4455 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) from originator [osservice<com.apple.FileCoordination>:650]
erreur	23:26:23.747884+0200	kernel	Sandbox: com.apple.quicklook.ThumbnailsA(893) deny(1) file-read-data /Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data/Library/Caches/Raivo OTP/raivo-debug-log.txt
erreur	23:26:23.749594+0200	kernel	Sandbox: com.apple.quicklook.ThumbnailsA(893) deny(1) file-issue-extension target:/Users/tabasko/Library/Containers/me.tij.Raivo-MacOS/Data/Library/Caches/Raivo OTP/raivo-debug-log.txt extension-class:com.apple.app-sandbox.read
par défaut	23:26:27.199233+0200	runningboardd	Assertion did invalidate due to timeout: 187-187-4434 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269])
par défaut	23:26:27.400018+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:26:27.400017+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:27.400124+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:27.400142+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:27.400229+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:32.159548+0200	Raivo OTP	LSExceptions shared instance invalidated for timeout.
par défaut	23:26:33.057707+0200	tccd	AUTHREQ_ATTRIBUTION: msgID=169.207, attribution={accessing={TCCDProcess: identifier=me.tij.Raivo-MacOS, pid=4269, auid=502, euid=502, binary_path=/Applications/Raivo OTP.app/Contents/MacOS/Raivo OTP}, requesting={TCCDProcess: identifier=com.apple.WindowServer, pid=169, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer}, },
par défaut	23:26:33.057780+0200	tccd	requestor: TCCDProcess: identifier=com.apple.WindowServer, pid=169, auid=88, euid=88, binary_path=/System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/Resources/WindowServer is checking access for accessor TCCDProcess: identifier=me.tij.Raivo-MacOS, pid=4269, auid=502, euid=502, binary_path=/Applications/Raivo OTP.app/Contents/MacOS/Raivo OTP
par défaut	23:26:33.059315+0200	tccd	AUTHREQ_SUBJECT: msgID=169.207, subject=me.tij.Raivo-MacOS,
par défaut	23:26:33.060389+0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier me.tij.Raivo-MacOS, type: 0: 0x7f94320dc380 at /Applications/Raivo OTP.app
erreur	23:26:33.067187+0200	Raivo OTP	Warning: Window NSMenuWindowManagerWindow 0x7fc422922320 ordered front from a non-active application and may order beneath the active application's windows.
par défaut	23:26:33.067306+0200	Raivo OTP	order window front conditionally: 359 related: 0
par défaut	23:26:35.665214+0200	Raivo OTP	order window: 359 op: 0 relative: 0 related: 0
erreur	23:26:35.747395+0200	Raivo OTP	Warning: Window Preferences.UserInteractionPausableWindow 0x7fc422833bf0 ordered front from a non-active application and may order beneath the active application's windows.
par défaut	23:26:35.747493+0200	Raivo OTP	order window front conditionally: 35a related: 0
par défaut	23:26:35.749484+0200	Raivo OTP	SetFrontProcess: asn=0x0-0xd00d0 options=1
par défaut	23:26:35.750490+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.coreservices.launchservicesd>:140] with description <RBSAssertionDescriptor| "frontmost:4269" ID:187-140-4471 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"RoleUserInteractiveFocal" sourceEnvironment:"(null)">
	]>
par défaut	23:26:35.750627+0200	runningboardd	Assertion 187-140-4471 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:35.752321+0200	Raivo OTP	SetFrontProcess: asn=0x0-0xd00d0 options=1
par défaut	23:26:35.753571+0200	Raivo OTP	order window: 359 op: 0 relative: 0 related: 0
par défaut	23:26:35.754575+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractiveFocal)
par défaut	23:26:35.755136+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:35.756196+0200	runningboardd	Acquiring assertion targeting [app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] from originator [osservice<com.apple.coreservices.launchservicesd>:140] with description <RBSAssertionDescriptor| "notification:4269" ID:187-140-4472 target:4269 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
par défaut	23:26:35.756493+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:35.757519+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Set darwin role to: UserInteractiveFocal
par défaut	23:26:35.757550+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:35.757586+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:35.756633+0200	runningboardd	Assertion 187-140-4472 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) will be created as active
par défaut	23:26:35.759779+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:35.759870+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:35.759912+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:35.759969+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:35.759394+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractiveFocal)
par défaut	23:26:35.797019+0200	Raivo OTP	order window front conditionally: 35a related: 0
par défaut	23:26:40.668045+0200	Raivo OTP	order window front conditionally: 35a related: 0
par défaut	23:26:40.670535+0200	Raivo OTP	SetFrontProcess: asn=0x0-0xd00d0 options=1
par défaut	23:26:41.740742+0200	runningboardd	Assertion did invalidate due to timeout: 187-140-4472 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269])
par défaut	23:26:41.939434+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractiveFocal)
par défaut	23:26:41.939563+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:26:41.939600+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:26:41.939631+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:26:41.939661+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
par défaut	23:26:46.791925+0200	Raivo OTP	LSExceptions shared instance invalidated for timeout.
par défaut	23:27:07.606353+0200	Raivo OTP	order window: 35a op: 0 relative: 0 related: 0
par défaut	23:27:28.281317+0200	runningboardd	Invalidating assertion 187-140-4471 (target:[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269]) from originator [osservice<com.apple.coreservices.launchservicesd>:140]
par défaut	23:27:28.388614+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring jetsam update because this process is not memory-managed
par défaut	23:27:28.388631+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring suspend because this process is not lifecycle managed
par défaut	23:27:28.388657+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Set darwin role to: UserInteractive
par défaut	23:27:28.388976+0200	runningboardd	Calculated state for app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>: running-active (role: UserInteractive)
par défaut	23:27:28.389015+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring GPU update because this process is not GPU managed
par défaut	23:27:28.390435+0200	runningboardd	[app<application.me.tij.Raivo-MacOS.13280778481.13280778498(502)>:4269] Ignoring memory limit update because this process is not memory-managed
`

**Comment by bruteForceAttack** [comment]
I don't know what has changed but on macos 13.3 everything works just well!

**Comment by tabasko78** [comment]
Ok, will filter tomorrow on "apsd" if not working I will reinstall ventura (I had some bugs after last update to 13.3 (nothing related to Raivo). Will keep you posted if the thread still opened.

**Comment by tabasko78** [comment]
Just re-installed ventura 13.3 , same issue.
Here is console log filtered APSD and RAIVO

is that more what you expected ?

[230330-Raivo.txt](https://github.com/raivo-otp/macos-receiver/files/11113982/230330-Raivo.txt)

**Comment by mcmehrtens** [comment]
> Hi there :) Just to tell that Ventura 13.4 doesn't fix situation for me. I'm still not able to you Raivo OTP on my iMac (2017 (Intel)).
> 
> Any news on this ?

Are you still having issues? Judging from the inactivity on this issue, it seems like macOS 13.3 resolved this issue for most users (including myself). Are you sure that a.) the Raivo OTP receiver application has been granted notification permissions and the notifications are configured correctly and b.) you don't have any focus modes or other settings enabled that would disable notifications?

The expected behavior is a brief banner to appear in the top-right corner of your screen saying, "Received password for <site name>" with your username listed underneath. The notifications do generally take a few seconds to appear.

If you're still having issues, enabling the iOS/macOS/iPadOS universal keyboard is an acceptable workaround for some users, unless you need the receiver to send notifications to multiple computers or function when your iPhone is not in network range or is using a different iCloud account.

I am using the developer beta for macOS 14.0 Sonoma, so the menu may look slightly different, but this is generally what your System Settings -> Notifications -> Raivo OTP settings view should look like (see attached screenshot).

<img width="500" alt="Screenshot 2023-06-28 at 00 12 54" src="https://github.com/raivo-otp/macos-receiver/assets/12023414/0d3c0855-9a7f-4484-a6ef-12d0fba76db8">

**Comment by tabasko78** [comment]
Thank you for writting me.
I've the same configuration : https://snipboard.io/kidXaZ.jpg

<img width="641" alt="image" src="https://github.com/raivo-otp/macos-receiver/assets/48969378/3854532e-0fed-4301-9c54-a1b391abf3b7">

**Comment by tabasko78** [comment]
I've tried several time to uninstall (using AppCleaner).
Am I supposed to installer a different version from the coming via AppStore ?

**Comment by tabasko78** [comment]
I'm here because my research brought me to this page. I'm not a dev, and I have the impression that if it's necessary to download the version from github, I'll have to recompile it, which I don't know how to do.

**Comment by tijme** [comment]
Hi @tabasko78, 

This still looks like a bug in MacOS to me. 2 days ago, I reached out to Apple Developer Support again to get a reply again, but until now, I did not get a useful response.

You cannot recompile the app. Well, technically you can, but I would need to sign in so you can actually receive notifications from Apple's push notification production server. Recompiling Raivo will not fix the issue though, I've tried.

I hope for your understanding. I'll let you know as soon as I have more information.

**Comment by tabasko78** [comment]
Ok thanks ! :(

**Comment by tabasko78** [comment]
Even in a fresh new macos user account it doesn't work :(

**Comment by tabasko78** [comment]
I have change my Raivo for another application. I couldn't bear the idea that my computer (the least mobile and therefore the least likely to be stolen) didn't have my OTP accounts. 

Thanks to everyone who tried to help me :)
